#GOLANG SETUP
FROM golang:alpine as builder

WORKDIR /go/src/app
COPY . .

RUN go get -d -v ./...
RUN go install -v ./...
RUN go build

FROM scratch

COPY --from=builder /go/src/app/app /

CMD ["/app"]
